language: python
sudo: false
python:
 - 2.7
 - 3.5
 - 3.6
env:
 - DJANGO='django>=1.3,<1.4'
 - DJANGO='django>=1.4,<1.5'
 - DJANGO='django>=1.5,<1.6'
 - DJANGO='django>=1.6,<1.7'
 - DJANGO='django>=1.7,<1.8'
 - DJANGO='django>=1.8,<1.9'
 - DJANGO='django>=1.9,<1.10'
 - DJANGO='django>=1.10,<1.11'
 - DJANGO='django>=1.11,<2.0'
install:
 - pip install $DJANGO django-classy-tags pep8 backport-collections
script: python runtests.py
notifications:
  email: false
matrix:
  exclude:
    - python: 3.5
      env: DJANGO='django>=1.3,<1.4'
    - python: 3.5
      env: DJANGO='django>=1.4,<1.5'
    - python: 3.5
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.5
      env: DJANGO='django>=1.6,<1.7'
    - python: 3.5
      env: DJANGO='django>=1.7,<1.8'
    - python: 3.6
      env: DJANGO='django>=1.3,<1.4'
    - python: 3.6
      env: DJANGO='django>=1.4,<1.5'
    - python: 3.6
      env: DJANGO='django>=1.5,<1.6'
    - python: 3.6
      env: DJANGO='django>=1.6,<1.7'
    - python: 3.6
      env: DJANGO='django>=1.7,<1.8'
